config/routes.rb
Rails.application.routes.draw do
  get "/", to: "ideas#index", as: :root
  post "/", to: "ideas#index"

  post "/idea", to: "ideas#new"
  get "/idea",      to: "ideas#new"

  post "/ideas/taken", to: "ideas#taken", as: :taken

end

app/models/idea.rb
class Idea < ActiveRecord::Base
  def self.random
    #rand_id = rand(Idea.count) + 1
    #Idea.find(rand_id).name
    Idea.limit(1).order("RANDOM()").each do |one|
      @huh = one.name
    end
    return @huh
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController

  def index
    #form for params view, to submit an idea
    if params[:thing] == 'next'
      render :ideagene
    end
  end

  def new
    @idea = Idea.new(params.require(:idea).permit(:name))
    if @idea.save
      redirect_to root_path
    else
      render :new
    end
  end

  def ideagene

  end

  def taken
    Idea.find_by(name: params[:info]).destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/views/ideas/_ideagene.html.erb
<div class= 'container'>

  <%= Idea.random%>
take it or leave it buttons.
if leave it == go to another random idea.
if take it redirect to HP with a flash message. 
</div>

app/views/ideas/_modal.html.erb
<div class = 'bodyit'>
<div class='modal-header'>
  <button type='button' class='close' data-dismiss='modal' aria-hidden='true'>x</button>
  <div class='modal-title'><h2><b><i>Submit an idea </i></b></h2></div>
</div>

<div class='modal-body'>
  <form action='idea' method='POST' role='form'>
    <div class = 'form-group'>
      <label for='ideaname'>Describe your idea:</label>
      <input type='text' name='idea[name]' class='form-control' placeholder='a brief description of your plan (one only please)' id='ideaname'/>
    </div>
  </div>

  <div class='modal-footer'>
    <input type='submit' value='Thanks for your submisson!' class='btn btn-primary'/>
  </form>
</div>
</div>

app/views/ideas/ideagene.html.erb
<div class= 'container'>
  <div class = 'linespaced'>
    <body class = "bodyit1">
      <%= Idea.random %>

      <div class="row">
      </br>
      </br>
          <div class="col-md-6"><%= button_to "Take it", taken_path(info: Idea.random) %> </div>
          <div class="col-md-6"> <%= button_to "Leave it", root_path(thing: "next") %></div>

      </div>
    </body>
  </div>
</div>

app/views/ideas/index.html.erb
<div class= 'container'>
</br>
</br>
</br>
</br>
</br>
</br>

  <div class = 'generator'>
    <div class = 'bodyit2'>
      <div class = 'maindrag'>
        Need an idea?
      </div>
    </div>
    </br>
    <div class= 'bodyit'>
      <%=button_to "Yes!", root_path(thing: "next"), class: "choose btn btn-success" %>
    </div>
  </div>


  <div class='thoughtsbox'>
    <div class='newidea'>
      <a href='javascript:void(0)' onClick="$('#modal-window').modal()">
        Submit an idea you'd like to see become a reality
      </a>
    </div>
  </div>


  <div id='modal-window' class='modal fade' role='dialog' aria-labelledby='myModalLabel' aria-hidden
  ='true' >
  <div class='modal-dialog'>
    <div class='modal-content'>
      <%= render 'ideas/modal'%>
    </div>
  </div>
</div>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <link href='http://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>

  <title>Randidea</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application'%>


  <div class="bg">
    <div class="mountain">
      <div class="mountain-top">
        <div class="mountain-cap-1"></div>
        <div class="mountain-cap-2"></div>
        <div class="mountain-cap-3"></div>
      </div>
    </div>
    <div class="mountain-two">
      <div class="mountain-top">
        <div class="mountain-cap-1"></div>
        <div class="mountain-cap-2"></div>
        <div class="mountain-cap-3"></div>
      </div>
    </div>
    <div class="mountain-three">
      <div class="mountain-top">
        <div class="mountain-cap-1"></div>
        <div class="mountain-cap-2"></div>
        <div class="mountain-cap-3"></div>
      </div>
    </div>
    
    <div class="cloud"></div>



   <div class="head-title">
      <center>
      <a href="/" class="link">
        <div class="first">random</div>
        <div><span class="second">idea</span><span class="third">generator</span></div> </center>
      </a>
    </div>

</head>


<body>




<%= yield %>













</div>

</body>
</html>